// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data_zset} from '../models';
import {model} from '../models';
import {data_list} from '../models';
import {data_set} from '../models';
import {data_string} from '../models';
import {data_hash} from '../models';
import {redis_init} from '../models';

export function AddZset(arg1:data_zset.ZsetData):Promise<model.SimpleResponse>;

export function AllKeyTypes():Promise<model.SimpleResponse>;

export function Del(arg1:string):Promise<model.SimpleResponse>;

export function DelListOne(arg1:data_list.ListData):Promise<model.SimpleResponse>;

export function DelSetOne(arg1:data_set.SetData):Promise<model.SimpleResponse>;

export function DelString(arg1:data_string.StringData):Promise<model.SimpleResponse>;

export function DelZsetOne(arg1:data_zset.ZsetData):Promise<model.SimpleResponse>;

export function GetHash(arg1:data_hash.HashData):Promise<model.SimpleResponse>;

export function GetList(arg1:data_list.ListData):Promise<model.SimpleResponse>;

export function GetSet(arg1:data_set.SetData):Promise<model.SimpleResponse>;

export function GetString(arg1:data_string.StringData):Promise<model.SimpleResponse>;

export function GetTTL(arg1:string):Promise<model.SimpleResponse>;

export function GetZset(arg1:data_zset.ZsetData):Promise<model.SimpleResponse>;

export function Greet(arg1:string):Promise<string>;

export function RedisInit(arg1:redis_init.RedisClient):Promise<model.SimpleResponse>;

export function SetKey(arg1:string,arg2:string):Promise<model.SimpleResponse>;

export function SetList(arg1:data_list.ListData):Promise<model.SimpleResponse>;

export function SetListSet(arg1:data_list.ListData):Promise<model.SimpleResponse>;

export function SetSet(arg1:data_set.SetData):Promise<model.SimpleResponse>;

export function SetString(arg1:data_string.StringData):Promise<model.SimpleResponse>;

export function SetTTL(arg1:string,arg2:string):Promise<model.SimpleResponse>;

export function SetZsetScore(arg1:data_zset.ZsetData):Promise<model.SimpleResponse>;

export function Test(arg1:any):Promise<any>;
