// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddZset(arg1) {
  return window['go']['main']['App']['AddZset'](arg1);
}

export function AllKeyTypes() {
  return window['go']['main']['App']['AllKeyTypes']();
}

export function Del(arg1) {
  return window['go']['main']['App']['Del'](arg1);
}

export function DelListOne(arg1) {
  return window['go']['main']['App']['DelListOne'](arg1);
}

export function DelSetOne(arg1) {
  return window['go']['main']['App']['DelSetOne'](arg1);
}

export function DelString(arg1) {
  return window['go']['main']['App']['DelString'](arg1);
}

export function DelZsetOne(arg1) {
  return window['go']['main']['App']['DelZsetOne'](arg1);
}

export function GetHash(arg1) {
  return window['go']['main']['App']['GetHash'](arg1);
}

export function GetList(arg1) {
  return window['go']['main']['App']['GetList'](arg1);
}

export function GetSet(arg1) {
  return window['go']['main']['App']['GetSet'](arg1);
}

export function GetString(arg1) {
  return window['go']['main']['App']['GetString'](arg1);
}

export function GetTTL(arg1) {
  return window['go']['main']['App']['GetTTL'](arg1);
}

export function GetZset(arg1) {
  return window['go']['main']['App']['GetZset'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RedisInit(arg1) {
  return window['go']['main']['App']['RedisInit'](arg1);
}

export function SetKey(arg1, arg2) {
  return window['go']['main']['App']['SetKey'](arg1, arg2);
}

export function SetList(arg1) {
  return window['go']['main']['App']['SetList'](arg1);
}

export function SetListSet(arg1) {
  return window['go']['main']['App']['SetListSet'](arg1);
}

export function SetSet(arg1) {
  return window['go']['main']['App']['SetSet'](arg1);
}

export function SetString(arg1) {
  return window['go']['main']['App']['SetString'](arg1);
}

export function SetTTL(arg1, arg2) {
  return window['go']['main']['App']['SetTTL'](arg1, arg2);
}

export function SetZsetScore(arg1) {
  return window['go']['main']['App']['SetZsetScore'](arg1);
}

export function Test(arg1) {
  return window['go']['main']['App']['Test'](arg1);
}
